#!/usr/bin/env python3

"""Generate a locally-mirrored nf-core test config.

nf-core pipelines ship a conf/test.config whose params point at
raw.githubusercontent.com URLs into the nf-core/test-datasets repo. Sites
like Hazel run compute jobs with no outbound internet, so `-profile test`
can't resolve those URLs there. When a local clone of the pipeline's
test-datasets branch is available (see download_nfcore_pipeline.sh
--with-testdata), this script rewrites every such URL in test.config --
and, recursively, in the samplesheet file that `input` points at, since
that also embeds the same URL pattern (e.g. per-sample fastq columns) --
to the matching local path. The result is a self-contained "local test
config" that a generated app can pass via `-c` instead of `-profile test`,
dropping the network dependency entirely.

Usage:
    gen_local_testconfig.py PIPELINE_DIR TESTDATA_DIR OUTPUT_CONFIG

Exits 0 without writing OUTPUT_CONFIG if PIPELINE_DIR has no
conf/test.config, TESTDATA_DIR doesn't exist, or test.config doesn't
reference nf-core/test-datasets URLs in the expected form -- this is a
best-effort feature layered on top of app generation, not a requirement
generation should fail without.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Matches any nf-core/test-datasets raw URL, whether pinned to a branch name
# or a commit SHA, e.g.:
#   https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/x
#   https://raw.githubusercontent.com/nf-core/test-datasets/<sha>/reference/y
# The matched span includes the trailing "/" so it splices directly into the
# local directory path with no separator bookkeeping at the call site.
URL_PATTERN = re.compile(
    r"https://raw\.githubusercontent\.com/nf-core/test-datasets/[^/'\"]+/"
)

# params whose value is itself a samplesheet/manifest file that may embed
# the same URL pattern (e.g. per-sample fastq_1/fastq_2 columns).
SAMPLESHEET_PARAMS = ("input",)


def rewrite(text: str, testdata_dir: Path) -> str:
    return URL_PATTERN.sub(f"{testdata_dir}/", text)


def localize_samplesheet(path_str: str, testdata_dir: Path, output_dir: Path) -> str | None:
    """If path_str is a local file with embedded test-datasets URLs, write a
    rewritten copy under output_dir and return its path. output_dir is the
    generated app's own template/ directory -- always owned by whoever's
    deploying the app -- rather than a sibling of the source file, which
    lives in the shared, service-account-owned testdata clone that a given
    deploy run may not have write access to (see nf2ood's
    stage_local_testconfig()). Returns None if the file doesn't exist or
    needed no rewriting.
    """
    path = Path(path_str)
    if not path.is_file():
        return None

    original = path.read_text(encoding="utf-8")
    localized = rewrite(original, testdata_dir)
    if localized == original:
        return None

    output_dir.mkdir(parents=True, exist_ok=True)
    local_path = output_dir / f"{path.stem}.local{path.suffix}"
    local_path.write_text(localized, encoding="utf-8")
    return str(local_path)


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(
            "usage: gen_local_testconfig.py PIPELINE_DIR TESTDATA_DIR OUTPUT_CONFIG\n"
        )
        return 1

    pipeline_dir = Path(sys.argv[1])
    testdata_dir = Path(sys.argv[2])
    output_path = Path(sys.argv[3])

    test_config = pipeline_dir / "conf" / "test.config"
    if not test_config.is_file() or not testdata_dir.is_dir():
        # No local test data staged for this pipeline (or it has no built-in
        # test.config at all) -- nothing to generate. The caller/runtime
        # treats a missing OUTPUT_CONFIG as "fall back to -profile test".
        return 0

    content = test_config.read_text(encoding="utf-8")
    localized = rewrite(content, testdata_dir)
    if localized == content:
        return 0

    for param in SAMPLESHEET_PARAMS:
        match = re.search(rf"""{param}\s*=\s*['"]([^'"]+)['"]""", localized)
        if not match:
            continue
        local_sheet = localize_samplesheet(match.group(1), testdata_dir, output_path.parent)
        if local_sheet:
            localized = (
                localized[: match.start(1)] + local_sheet + localized[match.end(1) :]
            )

    header = (
        "/*\n"
        "    Auto-generated by gen_local_testconfig.py -- do not edit by hand;\n"
        "    edits are overwritten the next time this app is regenerated.\n\n"
        f"    Local mirror of nf-core/{testdata_dir.name}'s conf/test.config: every\n"
        "    nf-core/test-datasets GitHub URL has been rewritten to a local\n"
        f"    path under {testdata_dir}\n"
        "    so this can be passed via `-c` in place of `-profile test`,\n"
        "    letting the test profile run with no outbound internet.\n"
        "*/\n\n"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header + localized, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
